### ISSUE TITLE
docker:10: command not found: docker not found

### ISSUE THREAD

**Issue by aankittcoolest** [tiangolo/babun-docker#26] opened 2017-02-21 06:55 UTC
STEPS FOLLOWED:

Open Babun terminal
<pre> echo $0 </pre>
Output: ✅
-zsh

<pre> curl -s https://raw.githubusercontent.com/tiangolo/babun-docker/master/setup.sh | source /dev/stdin </pre>

<pre> babun-docker-update </pre>
Output: ✅
-- babun-docker: Updating babun-docker
Already up-to-date.

<pre> docker ps </pre>
Output: ❌  
docker:10: command not found: docker not found

**Comment by tiangolo** [comment] 2017-02-21 13:21
@aankittcoolest did you install Docker Toolbox before?

**Comment by aankittcoolest** [comment] 2017-02-21 14:14
Yes I did. In fact I have returned back to it since docker-babun was not working.

**Comment by tiangolo** [comment] 2017-02-21 14:21
What do you get when you run `which docker`?

**Comment by aankittcoolest** [comment] 2017-02-21 14:25
It opens a script which looks something like this:
<pre>
docker () {
        if [[ -z ${babun_docker_old_IFS+x} ]]
        then
                babun_docker_old_IFS=$IFS
        fi
        if [[ -z ${babun_docker_volumes+x} ]]
        then
                babun_docker_volumes=$(ls /cygdrive)
        fi
        IFS=''
        babun_docker_use_winpty=0
        babun_docker_run_again=0
        "$docker_bin" $@ 2>&1 | while read -r line
        do
                echo $line
                if [[ $line == "cannot enable tty mode on non tty input" || $line == "the input device is not a TTY.  If you are using mintty, try prefixing the command with 'winpty'" || $line == "Error: Cannot perform an interactive login from a non TTY device" ]]
                then
                        babun_docker_use_winpty=1
                        echo "export babun_docker_use_winpty=1" >> $babun_docker_env_vars_file
                elif [[ $line == *"ConnectEx tcp"* || $line == *"connectex"* || $line == *"//./pipe/docker_engine:"* ]]
                then
                        if [[ $babun_docker_setup_volumes == 1 ]]
                        then
                                IFS=$babun_docker_old_IFS
                                if [[ -f "$babun_docker_virtualbox_bin" ]]
                                then
                                        for drive in $(echo $babun_docker_volumes | tr '\n' ' ')
                                        do
                                                windows_drive=$(cygpath -d /cygdrive/$drive)
                                                windows_driveb=$(cygpath -d /$drive)
                                                if [[ -z $("$babun_docker_virtualbox_bin" showvminfo $babun_docker_machine_name | grep "Name: '$drive'") ]]
                                                then
                                                        echo "$babun_docker_feedback Setting VirtualBox shared folder for drive $drive"
                                                        "$babun_docker_virtualbox_bin" sharedfolder add $babun_docker_machine_name --name $drive --hostpath $windows_drive --automount
                                                        "$babun_docker_virtualbox_bin" sharedfolder add $babun_docker_machine_name --name $drive --hostpath $windows_driveb --automount
                                                else
                                                        echo "$babun_docker_feedback VirtualBox shared folder for drive $drive was already set"
                                                fi
                                        done
                                fi
                                IFS=''
                        fi
                        echo "$babun_docker_feedback Trying to start docker-machine $babun_docker_machine_name"
                        docker-machine start $babun_docker_machine_name
                        if [[ $babun_docker_setup_volumes == 1 ]]
                        then
                                IFS=$babun_docker_old_IFS
                                for drive in $(ls /cygdrive)
                                do
                                        echo "$babun_docker_feedback Volumes, creating directory for drive: $drive"
                                        docker-machine ssh $babun_docker_machine_name "sudo mkdir -p /cygdrive/$drive/"
                                        docker-machine ssh $babun_docker_machine_name "sudo mkdir -p /$drive/"
                                        echo "$babun_docker_feedback Volumes, mounting drive: $drive"
                                        docker-machine ssh $babun_docker_machine_name 'sudo mount -t vboxsf -o "defaults,uid=`id -u docker`,gid=`id -g docker`,iocharset=utf8,rw"' "$drive /cygdrive/$drive/"
                                        docker-machine ssh $babun_docker_machine_name 'sudo mount -t vboxsf -o "defaults,uid=`id -u docker`,gid=`id -g docker`,iocharset=utf8,rw"' "$drive /$drive/"
                                done
                                IFS=''
                        fi
                        echo "$babun_docker_feedback Setting up docker-machine environment"
                        eval "$(docker-machine env $babun_docker_machine_name --shell bash)"
                        docker-machine env $babun_docker_machine_name --shell bash >> $babun_docker_env_vars_file
                        sed -i 's|\\|/|g' $babun_docker_env_vars_file
                        babun_docker_run_again=1
                        echo "export babun_docker_run_again=1" >> $babun_docker_env_vars_file
                fi
        done
        if [[ -f $babun_docker_env_vars_file ]]
        then
                source $babun_docker_env_vars_file
                rm $babun_docker_env_vars_file
        fi
        if [[ $babun_docker_use_winpty == 1 ]]
        then
                echo "$babun_docker_feedback Using winpty"
                winpty $docker_bin $@
        elif [[ $babun_docker_run_again == 1 ]]
        then
                echo "$babun_docker_feedback Running command again"
                docker $@
        fi
        IFS=$babun_docker_old_IFS
}
</pre>

**Comment by tiangolo** [comment] 2017-02-21 20:14
Interesting. That shows what it should. That big script is `babun-docker` itself.

Then it might be that babun-docker is being unable to find the Docker binary.

What do you get from: `echo $docker_bin`?

And what happens if you run: `$docker_bin ps`?

**Comment by aankittcoolest** [comment] 2017-02-22 14:32
Interesting!

<pre> echo $docker_bin </pre>

Results in "docker not found"
What explains that?

**Comment by StalkAlex** [comment] 2017-04-14 11:37
This is more interesting. Previous command returns me correct path. But `docker exec` is not working
```bash
the input device is not a TTY.  If you are using mintty, try prefixing the command with 'winpty'
-- babun-docker: Using winpty
Could not start '"C:/Program Files/Git/cygdrive/c/Program Files/Docker Toolbox/docker" exec -it app_php_1 bash': Не удается найти указанный файл. (error 0x2)
```
Message says that it was not able to find specified file. As we can see path is incorrect.

P.S. Created new issue as the problem is different.

**Comment by StalkAlex** [comment] 2017-04-14 12:02
Problem connected with docker machines run on other host like vSphere. 
```bash
  app git:(develop) ✗ docker-machine ls
NAME      ACTIVE   DRIVER          STATE     URL                        SWARM   DOCKER        ERRORS
default   -        virtualbox      Stopped                                      Unknown
vm        *        vmwarevsphere   Running   tcp://192.168.1.213:2376           v17.04.0-ce
```
As it can be seen I have vm started state. Then I want to `docker exec` one of my container.

 ```bash
Error response from daemon: No such container: app_php_1
```
By docker tutorial I need to do some actions.

```bash
➜  app git:(develop) ✗ docker-machine env vm
export DOCKER_TLS_VERIFY="1"
export DOCKER_HOST="tcp://192.168.1.213:2376"
export DOCKER_CERT_PATH="C:\Users\name\.docker\machine\machines\vm"
export DOCKER_MACHINE_NAME="vm"
export COMPOSE_CONVERT_WINDOWS_PATHS="true"
# Run this command to configure your shell:
# eval $("C:\Program Files\Docker Toolbox\docker-machine.exe" env vm)
```
It suggests to run command above. After that everything would work in standard docker terminal.
I ran this command, but had to modify path I thought
```bash
 eval $("/cygdrive/c/Program Files/Docker Toolbox/docker-machine.exe" env vm)
```
After this `ls` showed star symbol meaning it saw my machine
```bash
➜  app git:(develop) ✗ docker-machine ls
NAME      ACTIVE   DRIVER          STATE     URL                        SWARM   DOCKER        ERRORS
default   -        virtualbox      Stopped                                      Unknown
vm        *        vmwarevsphere   Running   tcp://192.168.1.213:2376           v17.04.0-ce
```
But `docker exec` failed
```bash
➜  app git:(develop) ✗ docker exec -it app_php_1 bash
time="2017-04-14T16:47:52+05:00" level=info msg="Unable to use system certificate pool: crypto/x509: system root pool is not available on Windows"
the input device is not a TTY.  If you are using mintty, try prefixing the command with 'winpty'
-- babun-docker: Using winpty
Could not start '"C:/Program Files/Git/cygdrive/c/Program Files/Docker Toolbox/docker" exec -it app_php_1 bash': Не удается найти указанный файл. (error 0x2)
```
It was not able find specified path, which seemed incorrect.

**Comment by tiangolo** [comment] 2017-04-14 14:58
@aankittcoolest first, sorry for the delay.

It seems like your `docker` binary is not in the `PATH` variable in Babun.

* When you run the normal Docker (Git Bash) terminal, when you type:

```bash
which docker
```

What do you get?

* In that same terminal, what do you get with?:

```bash
echo $PATH
```

* And in Babun, what do you get with?:

```bash
echo $PATH
```

**Comment by tiangolo** [comment] 2018-04-27 11:48
Since there were no more comments, I'll assume you solved your problem. I'll close this issue.

**Closed as completed by tiangolo** 2018-04-27 11:48 UTC

**Comment by y4hoo** [comment] 2018-09-14 08:18
> @aankittcoolest first, sorry for the delay.
> 
> It seems like your `docker` binary is not in the `PATH` variable in Babun.
> 
> * When you run the normal Docker (Git Bash) terminal, when you type:
> 
> ```shell
> which docker
> ```
> 
> What do you get?
> 
> * In that same terminal, what do you get with?:
> 
> ```shell
> echo $PATH
> ```
> 
> * And in Babun, what do you get with?:
> 
> ```shell
> echo $PATH
> ```

I have similiar problem while running docker from diffrent terminal 
I just added "/usr/local/bin/" path and it works.
thank yo for
